### ISSUE TITLE
[Testing Party] Question Filters

### ISSUE THREAD

**Issue by xiaolin-zhong** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-3#131]
test5
Username: zhu.jiumu+106@gmail.com
Password: password106

I filtered for company Meta, which had 22 pages of question. I went to page 22 then filtered for type Behavioral. Page is now blank despite the fact that those two filters should have questions in those categories. 

Then I tried changing the company filter to all other companies, none had any questions, like image shown.

![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/dda38443-3957-4694-8080-fb2b8a655ad6)

Then I changed the company filter to none. There seems to be pages now but still blank unless I click on one of the page numbers on the bottom.

![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/9baace83-7ea3-45b2-b29d-0f8e166231f7)

So I'm guessing if a user enters a page (presumably a high number page) that exists with (or without) a filter, then decides to change the filter with less results, the results will no longer display unless the user enters a page number that is within the results. 

There seems to be an extra none selection in the company, position, difficulty filter.
![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/d4aa65d6-0589-4622-a609-6d332c4a2ecc)

**Comment by zhujiumu** [comment]
we will fix this issue - thank you!
