### ISSUE TITLE
[Testing Party] Edit Profile

### ISSUE THREAD

**Issue by xiaolin-zhong** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-3#132]
test5
Username: zhu.jiumu+106@gmail.com
Password: password106

I had edited this profile with made up information. However, it accepted links that were not linkedin or github. 

In this case I simply gave it the web app's URL. Redirection when clicking the links works fine but may I suggest it opens a new tab rather than changing the current page URL?

![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/a0ebc0e7-73c5-4614-8aab-f74ee2e43ddd)

For 'Job Preference' field, I was able to put a number like so: 
![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/92e39745-7899-4e58-a58c-6a5b851e0672)

Also, there's a typo in the profile page. It says 'Job Perference'.

As for user experience, if I want to edit just one field of my profile, I am unable to. It forces me to reenter information I do not want to change.
![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/d8479454-de5c-40a9-83a0-00e824de3dce)

**Comment by zhujiumu** [comment]
Job Preference is just a string at the moment - we will look

**Comment by zhujiumu** [comment]
Thanks for the suggestions - we will implement them and fix the typos!
