### ISSUE TITLE
[Testing Party] Registration

### ISSUE THREAD

**Issue by xiaolin-zhong** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-3#133]
I was able to register two new account using zhu.jiumu+108@gmail.com & zhu.jiumu+109@gmail.com  and successfully logged in without doing any email verification.

![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/232b7d04-2751-46a2-8452-03ab87afc4f2)

Question, is there any difference between a student account vs hiring manager account?

**Comment by zhujiumu** [comment]
Login works even for unverified account(similar to the careers websites you visit when applying for jobs, verification is not needed to login), however some features such as password recovery only works if the user already verified their email.
